language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "node"
sudo: false
script:
  - if [ "x$BUNDLER" = "x" ]; then npm run test; fi
  - if [ "x$BUNDLER" != "x" ]; then npm run test-karma; fi
# only run karma tests for one node version
matrix:
  include:
  - name: "Browser Unit Tests"
    node_js: "12"
    env: BUNDLER=webpack
notifications:
  email:
    on_success: change
    on_failure: change
